local M = {}

M.boxes = {
	{
		horizontal = "─",
		vertical = "│",
		top_left = "┌",
		top_right = "┐",
		bottom_left = "└",
		bottom_right = "┘",
		horizontal_bottom = "─",
		vertical_right = "│",
	},
	{
		horizontal = "━",
		vertical = "┃",
		top_left = "┏",
		top_right = "┓",
		bottom_left = "┗",
		bottom_right = "┛",
		horizontal_bottom = "━",
		vertical_right = "┃",
	},
	{
		horizontal = "╌",
		vertical = "╎",
		top_left = "┌",
		top_right = "┐",
		bottom_left = "└",
		bottom_right = "┘",
		horizontal_bottom = "╌",
		vertical_right = "╎",
	},
	{
		horizontal = "╍",
		vertical = "╏",
		top_left = "┏",
		top_right = "┓",
		bottom_left = "┗",
		bottom_right = "┛",
		horizontal_bottom = "╍",
		vertical_right = "╏",
	},
	{
		horizontal = "━",
		vertical = "│",
		top_left = "┍",
		top_right = "┑",
		bottom_left = "┕",
		bottom_right = "┙",
		horizontal_bottom = "━",
		vertical_right = "│",
	},
	{
		horizontal = "═",
		vertical = "║",
		top_left = "╔",
		top_right = "╗",
		bottom_left = "╚",
		bottom_right = "╝",
		horizontal_bottom = "═",
		vertical_right = "║",
	},
	{
		horizontal = "═",
		vertical = "│",
		top_left = "╒",
		top_right = "╕",
		bottom_left = "╘",
		bottom_right = "╛",
		horizontal_bottom = "═",
		vertical_right = "│",
	},
	{
		horizontal = "─",
		vertical = "║",
		top_left = "╓",
		top_right = "╖",
		bottom_left = "╙",
		bottom_right = "╜",
		horizontal_bottom = "─",
		vertical_right = "║",
	},
	{
		horizontal = "-",
		vertical = "|",
		top_left = "+",
		top_right = "+",
		bottom_left = "+",
		bottom_right = "+",
		horizontal_bottom = "-",
		vertical_right = "|",
	},
	{
		horizontal = " ",
		vertical = "█",
		top_left = "▲",
		top_right = " ",
		bottom_left = "▼",
		bottom_right = " ",
		horizontal_bottom = " ",
		vertical_right = " ",
	},
	{
		horizontal = " ",
		vertical = "│",
		top_left = "┌",
		top_right = " ",
		bottom_left = "└",
		bottom_right = " ",
		horizontal_bottom = " ",
		vertical_right = " ",
	},
	{
		horizontal = " ",
		vertical = "║",
		top_left = "╓",
		top_right = " ",
		bottom_left = "╙",
		bottom_right = " ",
		horizontal_bottom = " ",
		vertical_right = " ",
	},
	{
		horizontal = " ",
		vertical = " ",
		top_left = " ",
		top_right = "▲",
		bottom_left = " ",
		bottom_right = "▼",
		horizontal_bottom = " ",
		vertical_right = "█",
	},
	{
		horizontal = " ",
		vertical = " ",
		top_left = " ",
		top_right = "┐",
		bottom_left = " ",
		bottom_right = "┘",
		horizontal_bottom = " ",
		vertical_right = "│",
	},
	{
		horizontal = " ",
		vertical = " ",
		top_left = " ",
		top_right = "╖",
		bottom_left = " ",
		bottom_right = "╜",
		horizontal_bottom = " ",
		vertical_right = "║",
	},
	{
		horizontal = " ",
		vertical = "█",
		top_left = "▲",
		top_right = "▲",
		bottom_left = "▼",
		bottom_right = "▼",
		horizontal_bottom = " ",
		vertical_right = "█",
	},
	{
		horizontal = " ",
		vertical = "│",
		top_left = "┌",
		top_right = "┐",
		bottom_left = "└",
		bottom_right = "┘",
		horizontal_bottom = " ",
		vertical_right = "│",
	},
	{
		horizontal = " ",
		vertical = "║",
		top_left = "╓",
		top_right = "╖",
		bottom_left = "╙",
		bottom_right = "╜",
		horizontal_bottom = " ",
		vertical_right = "║",
	},
	{
		horizontal = "─",
		vertical = " ",
		top_left = "┌",
		top_right = "┐",
		bottom_left = "└",
		bottom_right = "┘",
		horizontal_bottom = "─",
		vertical_right = " ",
	},
	{
		horizontal = "═",
		vertical = " ",
		top_left = "╒",
		top_right = "╕",
		bottom_left = "╘",
		bottom_right = "╛",
		horizontal_bottom = "═",
		vertical_right = " ",
	},
	{
		horizontal = "═",
		vertical = " ",
		top_left = "╒",
		top_right = "╕",
		bottom_left = "└",
		bottom_right = "┘",
		horizontal_bottom = "─",
		vertical_right = " ",
	},
}

M.lines = {
	{
		line = "━",
		line_start = "━",
		line_end = "━",
	},
	{
		line = "─",
		line_start = "├",
		line_end = "┤",
	},
	{
		line = "━",
		line_start = "┣",
		line_end = "┫",
	},
	{
		line = "─",
		line_start = "╾",
		line_end = "╼",
	},
	{
		line = "═",
		line_start = "═",
		line_end = "═",
	},
	{
		line = "═",
		line_start = "╞",
		line_end = "╡",
	},
	{
		line = "-",
		line_start = "-",
		line_end = "-",
	},
	{
		line = "_",
		line_start = "_",
		line_end = "_",
	},
	{
		line = "-",
		line_start = "+",
		line_end = "+",
	},
}
return M
