--          ╭─────────────────────────────────────────────────────────╮
--          │                         CATALOG                         │
--          ╰─────────────────────────────────────────────────────────╯

return {
  boxes = {
    {
      top = "─",
      bottom = "─",
      left = "│",
      right = "│",
      top_left = "╭",
      top_right = "╮",
      bottom_left = "╰",
      bottom_right = "╯",
    },
    {
      top = "─",
      bottom = "─",
      left = "│",
      right = "│",
      top_left = "┌",
      top_right = "┐",
      bottom_left = "└",
      bottom_right = "┘",
    },
    {
      top = "━",
      bottom = "━",
      left = "┃",
      right = "┃",
      top_left = "┏",
      top_right = "┓",
      bottom_left = "┗",
      bottom_right = "┛",
    },
    {
      top = "╌",
      bottom = "╌",
      left = "╎",
      right = "╎",
      top_left = "┌",
      top_right = "┐",
      bottom_left = "└",
      bottom_right = "┘",
    },
    {
      top = "╍",
      bottom = "╍",
      left = "╏",
      right = "╏",
      top_left = "┏",
      top_right = "┓",
      bottom_left = "┗",
      bottom_right = "┛",
    },
    {
      top = "━",
      bottom = "━",
      left = "│",
      right = "│",
      top_left = "┍",
      top_right = "┑",
      bottom_left = "┕",
      bottom_right = "┙",
    },
    {
      top = "═",
      bottom = "═",
      left = "║",
      right = "║",
      top_left = "╔",
      top_right = "╗",
      bottom_left = "╚",
      bottom_right = "╝",
    },
    {
      top = "═",
      bottom = "═",
      left = "│",
      right = "│",
      top_left = "╒",
      top_right = "╕",
      bottom_left = "╘",
      bottom_right = "╛",
    },
    {
      top = "─",
      bottom = "─",
      left = "║",
      right = "║",
      top_left = "╓",
      top_right = "╖",
      bottom_left = "╙",
      bottom_right = "╜",
    },
    {
      top = "-",
      bottom = "-",
      left = "|",
      right = "|",
      top_left = "+",
      top_right = "+",
      bottom_left = "+",
      bottom_right = "+",
    },
    {
      top = " ",
      bottom = " ",
      left = "█",
      right = " ",
      top_left = "▲",
      top_right = " ",
      bottom_left = "▼",
      bottom_right = " ",
    },
    {
      top = " ",
      bottom = " ",
      left = "│",
      right = " ",
      top_left = "┌",
      top_right = " ",
      bottom_left = "└",
      bottom_right = " ",
    },
    {
      top = " ",
      bottom = " ",
      left = "║",
      right = " ",
      top_left = "╓",
      top_right = " ",
      bottom_left = "╙",
      bottom_right = " ",
    },
    {
      top = " ",
      bottom = " ",
      left = " ",
      right = "█",
      top_left = " ",
      top_right = "▲",
      bottom_left = " ",
      bottom_right = "▼",
    },
    {
      top = " ",
      bottom = " ",
      left = " ",
      right = "│",
      top_left = " ",
      top_right = "┐",
      bottom_left = " ",
      bottom_right = "┘",
    },
    {
      top = " ",
      bottom = " ",
      left = " ",
      right = "║",
      top_left = " ",
      top_right = "╖",
      bottom_left = " ",
      bottom_right = "╜",
    },
    {
      top = " ",
      bottom = " ",
      left = "█",
      right = "█",
      top_left = "▲",
      top_right = "▲",
      bottom_left = "▼",
      bottom_right = "▼",
    },
    {
      top = " ",
      bottom = " ",
      left = "│",
      right = "│",
      top_left = "┌",
      top_right = "┐",
      bottom_left = "└",
      bottom_right = "┘",
    },
    {
      top = " ",
      bottom = " ",
      left = "║",
      right = "║",
      top_left = "╓",
      top_right = "╖",
      bottom_left = "╙",
      bottom_right = "╜",
    },
    {
      top = "─",
      bottom = "─",
      left = " ",
      right = " ",
      top_left = "┌",
      top_right = "┐",
      bottom_left = "└",
      bottom_right = "┘",
    },
    {
      top = "═",
      bottom = "═",
      left = " ",
      right = " ",
      top_left = "╒",
      top_right = "╕",
      bottom_left = "╘",
      bottom_right = "╛",
    },
    {
      top = "═",
      bottom = "─",
      left = " ",
      right = " ",
      top_left = "╒",
      top_right = "╕",
      bottom_left = "└",
      bottom_right = "┘",
    },
  },

  lines = {
    {
      line = "─",
      line_start = "─",
      line_end = "─",
      title_left = "─",
      title_right = "─",
    },
    {
      line = "─",
      line_start = "─",
      line_end = "─",
      title_left = "[",
      title_right = "]",
    },
    {
      line = "─",
      line_start = "─",
      line_end = "─",
      title_left = "(",
      title_right = ")",
    },
    {
      line = "─",
      line_start = "─",
      line_end = "─",
      title_left = "<",
      title_right = ">",
    },
    {
      line = "━",
      line_start = "━",
      line_end = "━",
      title_left = "━",
      title_right = "━",
    },
    {
      line = "─",
      line_start = "├",
      line_end = "┤",
      title_left = "┤",
      title_right = "├",
    },
    {
      line = "━",
      line_start = "┣",
      line_end = "┫",
      title_left = "┫",
      title_right = "┣",
    },
    {
      line = "─",
      line_start = "╾",
      line_end = "╼",
      title_left = "╼",
      title_right = "╾",
    },
    {
      line = "═",
      line_start = "═",
      line_end = "═",
      title_left = "═",
      title_right = "═",
    },
    {
      line = "═",
      line_start = "╞",
      line_end = "╡",
      title_left = "╡",
      title_right = "╞",
    },
    {
      line = "-",
      line_start = "-",
      line_end = "-",
      title_left = "-",
      title_right = "-",
    },
    {
      line = "_",
      line_start = "_",
      line_end = "_",
      title_left = "_",
      title_right = "_",
    },
    {
      line = "-",
      line_start = "+",
      line_end = "+",
      title_left = "+",
      title_right = "+",
    },
  },
}
